// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:54339bdf-5a41-4e9d-9366-628f6b5fae3d",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_8h7nSR2S1",
    "aws_user_pools_web_client_id": "3vkvlra0spoj7ouns4va2ar1e7",
    "oauth": {
        "domain": "zeptron-master.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.zeptron.co/",
        "redirectSignOut": "https://www.zeptron.co/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://4sdmpybta5gjvhc5hrwzshxnwq.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hlvvjzglyzcvnas46vgk3l6xx4"
};


export default awsmobile;
