// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:3494f1e1-39a5-4f81-9e7b-4382ffcf1c2f",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_kO2zTh8Js",
    "aws_user_pools_web_client_id": "7a0k10c80amtalh90iok5q80ue",
    "oauth": {
        "domain": "zepd1ad591a-d1ad591a-staging.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://staging.zeptron.co/",
        "redirectSignOut": "https://staging.zeptron.co/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://dwh2ekous5fwbgptsa3qcjx47i.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xhlu7uv3p5f37c6yl6c2fp56gm"
};


export default awsmobile;
